title: Neeli Mishra
logo: "/images/neeli_rquare.png?raw=true"
description: > # your text below (remove <br> elements if you don't need line breaks)
  I am a postdoctoral research scientist working with <a href="http://www.columbia.edu/cu/neurotheory/Larry/">Larry Abbott</a> in the <a href="https://ctn.zuckermaninstitute.columbia.edu/">Center for Theoretical Neuroscience</a> at <a href="https://www.columbia.edu/">Columbia University</a> in NYC. My research focuses on understanding computation in the brain and in ANNs by analyzing the geometries of neural and feature representations in neural networks.   
  <br><br>
  Previously, I completed my Ph.D. in <a href="https://www.neurosciencephd.columbia.edu/">Neurobiology and Behavior</a> at Columbia University, where I was supervised by <a href="https://zuckermaninstitute.columbia.edu/richard-axel-md">Richard Axel</a>. My research focused on using techniques from computer vision, machine learning and statistics to analyze large neural and behavioral datasets. Before this, I studied <a href="https://www.be.caltech.edu/">bioengineering</a> at <a href="https://www.caltech.edu/">Caltech</a> in Pasadena, California. 
  <br><br>
  You can contact me at nm2786 [at] columbia [dot] edu.

  <a href="https://github.com/neelimishra">GitHub</a>
  <a href="https://www.linkedin.com/in/neelimishra/">LinkedIn</a> 

  
theme: jekyll-theme-minimal
markdown: kramdown
plugins:
  - jemoji

